# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scale_mat_col <- function(mat, scale) {
    .Call('_umfpackr_scale_mat_col', PACKAGE = 'umfpackr', mat, scale)
}

umf_solve_ <- function(a, b) {
    .Call('_umfpackr_umf_solve_', PACKAGE = 'umfpackr', a, b)
}

