# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve linear equation using UMFPACK
#'
#' @param A a \code{dgCMatrix}
#' @param b the right hand side of A x = b
#' @return x the solution x.
#' @export
#' @useDynLib umfpackr
#' @importFrom Rcpp sourceCpp
umf_solve <- function(a, b) {
    .Call('umfpackr_umf_solve', PACKAGE = 'umfpackr', a, b)
}

