# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solves the system of linear equations \eqn{A x = b} using UMFPACK
#'
#' @param a a \code{dgCMatrix}
#' @param b the vector \eqn{b}
#' @return x the solution \eqn{x}
#' @export
#' @useDynLib umfpackr
#' @importFrom Rcpp sourceCpp
umf_solve <- function(a, b) {
    .Call('umfpackr_umf_solve', PACKAGE = 'umfpackr', a, b)
}

umf_solve_nl_ <- function(start, fn, jac, control) {
    .Call('umfpackr_umf_solve_nl_', PACKAGE = 'umfpackr', start, fn, jac, control)
}

