// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// umf_solve_
List umf_solve_(S4 a, NumericVector b, const double cndtol);
RcppExport SEXP _umfpackr_umf_solve_(SEXP aSEXP, SEXP bSEXP, SEXP cndtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type cndtol(cndtolSEXP);
    rcpp_result_gen = Rcpp::wrap(umf_solve_(a, b, cndtol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_umfpackr_umf_solve_", (DL_FUNC) &_umfpackr_umf_solve_, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_umfpackr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
